version: '2'
services:
  db:
    image: mysql:5.7.11
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD='yes'
    volumes:
      - /var/lib/mysql
  web:
    build: .
    ports:
      - "80:80"
    depends_on:
      - db
